const fs = require('fs');
const path = require('path');
const nodemailer = require('nodemailer');
const https = require('https');
const http = require('http');
const db = require('./db');

let mailer = null;

function initializeMailer(config) {
  if (!config.smtp || !config.smtp.user || !config.smtp.password) {
    return null;
  }

  try {
    mailer = nodemailer.createTransport({
      host: config.smtp.host,
      port: config.smtp.port,
      secure: config.smtp.secure,
      auth: {
        user: config.smtp.user,
        pass: config.smtp.password
      }
    });
  } catch (e) {
    console.error('Failed to initialize mailer:', e);
    return null;
  }

  return mailer;
}

function sendEmail(prompt, output, config) {
  if (!mailer) {
    throw new Error('Email not configured. Please configure SMTP settings.');
  }

  const emailConfig = prompt.output_config;
  console.log('[sendEmail] output_config raw:', JSON.stringify(prompt.output_config), 'type:', typeof prompt.output_config);
  if (!emailConfig || !emailConfig.to) {
    throw new Error('Email recipient not specified in output config');
  }

  const now = new Date().toLocaleString();
  const subject = `[claudecron] ${prompt.name} - ${now}`;

  const htmlOutput = output
    .split('\n')
    .map(line => {
      const escaped = line
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
      return `<p>${escaped}</p>`;
    })
    .join('');

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background-color: #f5f5f5; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
          .header h2 { margin: 0 0 5px 0; color: #000; }
          .header p { margin: 0; color: #666; font-size: 12px; }
          .output { background-color: #fafafa; padding: 15px; border-radius: 5px; border-left: 4px solid #007bff; overflow-x: auto; }
          .output p { margin: 5px 0; line-height: 1.5; white-space: pre-wrap; word-break: break-word; }
          .footer { margin-top: 20px; padding-top: 15px; border-top: 1px solid #eee; font-size: 11px; color: #999; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h2>${prompt.name}</h2>
            <p>Scheduled prompt execution result</p>
          </div>
          <div class="output">
            ${htmlOutput}
          </div>
          <div class="footer">
            <p>This email was generated by claudecron</p>
          </div>
        </div>
      </body>
    </html>
  `;

  return new Promise((resolve, reject) => {
    mailer.sendMail(
      {
        from: config.defaultFrom,
        to: emailConfig.to,
        subject,
        html
      },
      (err, info) => {
        if (err) {
          console.error('Email send error:', err);
          reject(err);
        } else {
          console.log('Email sent:', info.response);
          resolve(info);
        }
      }
    );
  });
}

function appendToFile(prompt, output) {
  const filePath = prompt.output_config?.path;
  if (!filePath) {
    throw new Error('File path not specified in output config');
  }

  // Resolve relative paths to current working directory
  const resolvedPath = path.isAbsolute(filePath)
    ? filePath
    : path.join(process.cwd(), filePath);

  // Ensure directory exists
  const dir = path.dirname(resolvedPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const timestamp = new Date().toISOString();
  const entry = `\n\n--- ${prompt.name} - ${timestamp} ---\n${output}`;

  fs.appendFileSync(resolvedPath, entry, 'utf-8');
  console.log(`Output appended to: ${resolvedPath}`);
}

function sendToWebhook(prompt, output, status, error) {
  const webhookUrl = prompt.output_config?.url;
  if (!webhookUrl) {
    throw new Error('Webhook URL not specified in output config');
  }

  const payload = {
    timestamp: new Date().toISOString(),
    prompt: {
      id: prompt.id,
      name: prompt.name
    },
    status,
    output,
    error
  };

  return new Promise((resolve, reject) => {
    const url = new URL(webhookUrl);
    const isHttps = url.protocol === 'https:';
    const client = isHttps ? https : http;

    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(JSON.stringify(payload))
      }
    };

    const req = client.request(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => {
        data += chunk;
      });
      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          console.log(`Webhook sent to: ${webhookUrl}, status: ${res.statusCode}`);
          resolve({ statusCode: res.statusCode, body: data });
        } else {
          console.error(`Webhook error: ${res.statusCode}`);
          reject(new Error(`Webhook returned status ${res.statusCode}`));
        }
      });
    });

    req.on('error', (err) => {
      console.error('Webhook error:', err);
      reject(err);
    });

    req.write(JSON.stringify(payload));
    req.end();
  });
}

async function routeOutput(prompt, output, status, error) {
  if (!prompt.enabled) {
    return; // Don't route if prompt is disabled
  }

  const outputType = prompt.output_type;
  console.log(`Routing output for prompt "${prompt.name}" to: ${outputType}`);

  try {
    if (outputType === 'email') {
      await sendEmail(prompt, output, db.getConfig());
    } else if (outputType === 'file') {
      appendToFile(prompt, output);
    } else if (outputType === 'webhook') {
      await sendToWebhook(prompt, output, status, error);
    }
    // 'log' type just stores in database, which is already done
  } catch (err) {
    console.error(`Error routing output (${outputType}):`, err);
    // Don't re-throw; we want to log the error but not fail the run
  }
}

module.exports = {
  initializeMailer,
  sendEmail,
  appendToFile,
  sendToWebhook,
  routeOutput
};
